### ISSUE TITLE
Possible conflict with Aquaculture

### ISSUE THREAD

**Issue by dragoneyeeon** [tristankechlo/RandomMobSizes#1]
During developing a modpack the below error continued to persist while using RandomMobSizes alongside Aquaculture2.  This also disabled the spawning of all aquaculture2 natural spawned fish.

[09:39:19] [Server thread/WARN] [minecraft/NaturalSpawner]: Failed to create mob
java.lang.IllegalArgumentException: Duplicate id value for 17!
        at net.minecraft.network.syncher.SynchedEntityData.m_135372_(SynchedEntityData.java:82) ~[server-1.19.3-20221207.122022-srg.jar%23761!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:tumbleweed.mixins.json:SynchedDataAccessor,pl:mixin:A}
        at net.minecraft.world.entity.animal.AbstractFish.m_8097_(AbstractFish.java:72) ~[server-1.19.3-20221207.122022-srg.jar%23761!/:?] {re:classloading}
        at net.minecraft.world.entity.Entity.<init>(Entity.java:254) ~[server-1.19.3-20221207.122022-srg.jar%23761!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:openpartiesandclaims:xaero_pac_entity_handlenetherportal,xf:fml:openpartiesandclaims:xaero_pac_entity_isinvulnerable,xf:fml:openpartiesandclaims:xaero_pac_entity,re:computing_frames,pl:accesstransformer:B,xf:fml:openpartiesandclaims:xaero_pac_entity_handlenetherportal,xf:fml:openpartiesandclaims:xaero_pac_entity_isinvulnerable,xf:fml:openpartiesandclaims:xaero_pac_entity,re:classloading,pl:accesstransformer:B,xf:fml:openpartiesandclaims:xaero_pac_entity_handlenetherportal,xf:fml:openpartiesandclaims:xaero_pac_entity_isinvulnerable,xf:fml:openpartiesandclaims:xaero_pac_entity,pl:mixin:APP:ad_astra_giselle_addon.mixin.common.json:minecraft.EntityMixin,pl:mixin:APP:mixins.shetiphiancore.json:SPC_ThinBlockHandler$_Entity,pl:mixin:APP:structure_gel.mixins.json:EntityMixin,pl:mixin:APP:curios.mixins.json:AccessorEntity,pl:mixin:APP:pehkui.mixins.json:EntityMixin,pl:mixin:APP:pehkui.mixins.json:compat116plus.EntityMixin,pl:mixin:APP:pehkui.mixins.json:compat117plus.EntityMixin,pl:mixin:APP:pehkui.mixins.json:step_height.compat1193minus.EntityMixin,pl:mixin:APP:mixins.pneumaticcraft.json:accessors.EntityAccess,pl:mixin:APP:companion.mixins.json:EntityAccess,pl:mixin:APP:companion.mixins.json:EntityMixin,pl:mixin:APP:random_mob_sizes.mixins.json:EntityMixin,pl:mixin:APP:ad_astra-common.mixins.json:EntityInvoker,pl:mixin:APP:ad_astra-common.mixins.json:EntityMixin,pl:mixin:APP:netherportalfix.mixins.json:EntityAccessor,pl:mixin:APP:bookshelf.common.mixins.json:entity.AccessorEntity,pl:mixin:APP:carryon.mixins.json:EntityMixin,pl:mixin:APP:mixins.artifacts.json:item.aquadashers.EntityMixin,pl:mixin:APP:mixins.artifacts.json:item.umbrella.EntityMixin,pl:mixin:APP:expandability.mixins.json:swimming.EntityMixin,pl:mixin:APP:expandability-common.mixins.json:fluidcollision.EntityMixin,pl:mixin:APP:expandability-common.mixins.json:swimming.EntityMixin,pl:mixin:APP:rayon.mixins.json:common.entity.EntityMixin,pl:mixin:APP:assets/sound_physics_remastered/sound_physics_remastered.mixins.json:EntityMixin,pl:mixin:APP:pehkui.mixins.json:compat117plus.patchwork.compat.EntityCalculateDimensionsMixin,pl:mixin:A}
        at net.minecraft.world.entity.LivingEntity.<init>(LivingEntity.java:235) ~[server-1.19.3-20221207.122022-srg.jar%23761!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:openpartiesandclaims:xaero_pac_livingentity_addeffect,xf:fml:openpartiesandclaims:xaero_pac_livingentity_die,xf:fml:openpartiesandclaims:xaero_pac_livingentity_dropalldeathloot,re:classloading,pl:accesstransformer:B,xf:fml:openpartiesandclaims:xaero_pac_livingentity_addeffect,xf:fml:openpartiesandclaims:xaero_pac_livingentity_die,xf:fml:openpartiesandclaims:xaero_pac_livingentity_dropalldeathloot,pl:mixin:APP:ad_astra_giselle_addon.mixin.common.json:minecraft.LivingEntityMixin,pl:mixin:APP:immersive_armors.mixins.json:MixinLivingEntity,pl:mixin:APP:mixins.shetiphiancore.json:SPC_ThinBlockHandler$_LivingEntity,pl:mixin:APP:curios.mixins.json:MixinLivingEntity,pl:mixin:APP:cgm.mixins.json:common.LivingEntityMixin,pl:mixin:APP:pehkui.mixins.json:LivingEntityMixin,pl:mixin:APP:pehkui.mixins.json:compat116plus.compat1193minus.LivingEntityMixin,pl:mixin:APP:pehkui.mixins.json:compat117plus.LivingEntityMixin,pl:mixin:APP:caelus.mixins.json:MixinLivingEntity,pl:mixin:APP:citadel.mixins.json:LivingEntityMixin,pl:mixin:APP:iwannaskate.mixins.json:LivingEntityMixin,pl:mixin:APP:companion.mixins.json:LivingEntityMixin,pl:mixin:APP:ecologics-common.mixins.json:LivingEntityMixin,pl:mixin:APP:ad_astra-common.mixins.json:LivingEntityMixin,pl:mixin:APP:ad_astra-common.mixins.json:gravity.LivingEntityGravityMixin,pl:mixin:APP:blue_skies.mixins.json:LivingEntityMixin,pl:mixin:APP:netherportalfix.mixins.json:LivingEntityAccessor,pl:mixin:APP:bookshelf.common.mixins.json:entity.AccessorLivingEntity,pl:mixin:APP:bookshelf.common.mixins.json:entity.MixinLivingEntity,pl:mixin:APP:betterdeserttemples.mixins.json:PharaohKilledMixin,pl:mixin:APP:charmofundying.mixins.json:MixinLivingEntity,pl:mixin:APP:expandability.mixins.json:swimming.LivingEntityMixin,pl:mixin:APP:expandability-common.mixins.json:swimming.LivingEntityMixin,pl:mixin:APP:scena.mixins.json:common.LivingEntityEquipmentSlotMixin,pl:mixin:APP:pehkui.mixins.json:compat115plus.LivingEntityMixin,pl:mixin:A}
        at net.minecraft.world.entity.Mob.<init>(Mob.java:121) ~[server-1.19.3-20221207.122022-srg.jar%23761!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:openpartiesandclaims:xaero_pac_mob_aistep,xf:fml:syp:MobEntity,re:classloading,pl:accesstransformer:B,xf:fml:openpartiesandclaims:xaero_pac_mob_aistep,xf:fml:syp:MobEntity,pl:mixin:APP:immersive_armors.mixins.json:MobEntityMixin,pl:mixin:APP:pehkui.mixins.json:MobEntityMixin,pl:mixin:APP:mixins.pneumaticcraft.json:accessors.MobAccess,pl:mixin:APP:random_mob_sizes.mixins.json:MobMixin,pl:mixin:APP:bookshelf.common.mixins.json:entity.AccessorMob,pl:mixin:APP:letmedespawn.mixins.json:MobMixin,pl:mixin:APP:tumbleweed.mixins.json:MobAccessor,pl:mixin:APP:scuba_gear.mixins.json:MobEntityMixin,pl:mixin:APP:pehkui.mixins.json:compat116plus.MobEntityMixin,pl:mixin:A}
        at net.minecraft.world.entity.PathfinderMob.<init>(PathfinderMob.java:14) ~[server-1.19.3-20221207.122022-srg.jar%23761!/:?] {re:computing_frames,re:mixin,re:classloading}
        at net.minecraft.world.entity.animal.WaterAnimal.<init>(WaterAnimal.java:21) ~[server-1.19.3-20221207.122022-srg.jar%23761!/:?] {re:classloading,re:mixin}
        at net.minecraft.world.entity.animal.AbstractFish.<init>(AbstractFish.java:38) ~[server-1.19.3-20221207.122022-srg.jar%23761!/:?] {re:classloading}
        at net.minecraft.world.entity.animal.AbstractSchoolingFish.<init>(AbstractSchoolingFish.java:22) ~[server-1.19.3-20221207.122022-srg.jar%23761!/:?] {re:classloading,pl:accesstransformer:B}
        at com.teammetallurgy.aquaculture.entity.AquaFishEntity.<init>(AquaFishEntity.java:35) ~[Aquaculture-1.19.3-2.4.11.jar%23454!/:1.19.3-2.4.11] {re:classloading}
        at com.teammetallurgy.aquaculture.init.FishRegistry.lambda$register$2(FishRegistry.java:62) ~[Aquaculture-1.19.3-2.4.11.jar%23454!/:1.19.3-2.4.11] {re:classloading}
        at net.minecraft.world.entity.EntityType.m_20615_(EntityType.java:517) ~[server-1.19.3-20221207.122022-srg.jar%23761!/:?] {re:mixin,re:classloading,pl:mixin:APP:dangerousstonecutter-common.mixins.json:EntityTypeMixin,pl:mixin:APP:architectury-common.mixins.json:inject.MixinEntityType,pl:mixin:A}
        at net.minecraft.world.level.NaturalSpawner.m_46988_(NaturalSpawner.java:234) ~[server-1.19.3-20221207.122022-srg.jar%23761!/:?] {re:classloading}
        at net.minecraft.world.level.NaturalSpawner.m_47038_(NaturalSpawner.java:170) ~[server-1.19.3-20221207.122022-srg.jar%23761!/:?] {re:classloading}
        at net.minecraft.world.level.NaturalSpawner.m_47045_(NaturalSpawner.java:119) ~[server-1.19.3-20221207.122022-srg.jar%23761!/:?] {re:classloading}
        at net.minecraft.world.level.NaturalSpawner.m_47029_(NaturalSpawner.java:109) ~[server-1.19.3-20221207.122022-srg.jar%23761!/:?] {re:classloading}
        at net.minecraft.server.level.ServerChunkCache.m_8490_(ServerChunkCache.java:357) ~[server-1.19.3-20221207.122022-srg.jar%23761!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:smoothchunk.mixins.json:ServerChunkCacheMixin,pl:mixin:A}
        at net.minecraft.server.level.ServerChunkCache.m_201698_(ServerChunkCache.java:311) ~[server-1.19.3-20221207.122022-srg.jar%23761!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:smoothchunk.mixins.json:ServerChunkCacheMixin,pl:mixin:A}
        at net.minecraft.server.level.ServerLevel.m_8793_(ServerLevel.java:289) ~[server-1.19.3-20221207.122022-srg.jar%23761!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:openpartiesandclaims:xaero_pac_serverlevel_tick,xf:fml:forgeendertech:coremod,xf:fml:openpartiesandclaims:xaero_pac_serverlevel_ispositionentityticking,re:classloading,pl:accesstransformer:B,xf:fml:openpartiesandclaims:xaero_pac_serverlevel_tick,xf:fml:forgeendertech:coremod,xf:fml:openpartiesandclaims:xaero_pac_serverlevel_ispositionentityticking,pl:mixin:APP:pluto.mixins.json:fast_entity_access.ServerLevelMixin,pl:mixin:APP:citadel.mixins.json:ServerLevelMixin,pl:mixin:APP:ad_astra-common.mixins.json:ServerLevelMixin,pl:mixin:APP:observable.common.json:ServerLevelMixin,pl:mixin:APP:betterdeserttemples.mixins.json:ServerLevelMixin,pl:mixin:APP:friendsandfoes-common.mixins.json:ServerWorldAccessor,pl:mixin:APP:friendsandfoes-common.mixins.json:ServerWorldMixin,pl:mixin:APP:toolbox.mixins.json:common.ServerLevelMixin,pl:mixin:A}
        at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:876) ~[server-1.19.3-20221207.122022-srg.jar%23761!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:openpartiesandclaims:xaero_pac_minecraftserverclass,re:classloading,pl:accesstransformer:B,xf:fml:openpartiesandclaims:xaero_pac_minecraftserverclass,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:APP:fastload.mixins.json:server.MinecraftServerMixin,pl:mixin:APP:ae2.mixins.json:spatial.MinecraftServerMixin,pl:mixin:APP:citadel.mixins.json:MinecraftServerMixin,pl:mixin:APP:nabba.mixins.json:MinecraftServerAccess,pl:mixin:APP:toolbox.mixins.json:common.MinecraftServerMixin,pl:mixin:A}
        at net.minecraft.server.dedicated.DedicatedServer.m_5703_(DedicatedServer.java:273) ~[server-1.19.3-20221207.122022-srg.jar%23761!/:?] {re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
        at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:816) ~[server-1.19.3-20221207.122022-srg.jar%23761!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:openpartiesandclaims:xaero_pac_minecraftserverclass,re:classloading,pl:accesstransformer:B,xf:fml:openpartiesandclaims:xaero_pac_minecraftserverclass,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:APP:fastload.mixins.json:server.MinecraftServerMixin,pl:mixin:APP:ae2.mixins.json:spatial.MinecraftServerMixin,pl:mixin:APP:citadel.mixins.json:MinecraftServerMixin,pl:mixin:APP:nabba.mixins.json:MinecraftServerAccess,pl:mixin:APP:toolbox.mixins.json:common.MinecraftServerMixin,pl:mixin:A}
        at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:664) ~[server-1.19.3-20221207.122022-srg.jar%23761!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:openpartiesandclaims:xaero_pac_minecraftserverclass,re:classloading,pl:accesstransformer:B,xf:fml:openpartiesandclaims:xaero_pac_minecraftserverclass,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:APP:fastload.mixins.json:server.MinecraftServerMixin,pl:mixin:APP:ae2.mixins.json:spatial.MinecraftServerMixin,pl:mixin:APP:citadel.mixins.json:MinecraftServerMixin,pl:mixin:APP:nabba.mixins.json:MinecraftServerAccess,pl:mixin:APP:toolbox.mixins.json:common.MinecraftServerMixin,pl:mixin:A}
        at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:251) ~[server-1.19.3-20221207.122022-srg.jar%23761!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:openpartiesandclaims:xaero_pac_minecraftserverclass,re:classloading,pl:accesstransformer:B,xf:fml:openpartiesandclaims:xaero_pac_minecraftserverclass,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:APP:fastload.mixins.json:server.MinecraftServerMixin,pl:mixin:APP:ae2.mixins.json:spatial.MinecraftServerMixin,pl:mixin:APP:citadel.mixins.json:MinecraftServerMixin,pl:mixin:APP:nabba.mixins.json:MinecraftServerAccess,pl:mixin:APP:toolbox.mixins.json:common.MinecraftServerMixin,pl:mixin:A}
        at java.lang.Thread.run(Thread.java:833) ~[?:?] {re:mixin}

**Comment by tristankechlo** [comment]
which minecraft and modversion are you using?  
  
also for future reference pls don't just paste the logs here, really hard to read

**Comment by dragoneyeeon** [comment]
This was running mc 1.19.3(forge44.1.23), mod version 1.19.3-1.1.  Alongside aquaculture2 version 1.19.3-2.4.11.  Sorry for the log in that format, I should have previewed the message before submitting it.

**Comment by tristankechlo** [comment]
oh, looks like I forgot about 1.19.3, in all other versions its already fixed  
checkout modversion 1.19.3-1.1.1, it should fix this issue

**Comment by dragoneyeeon** [comment]
Sorry I never posted back on this issue, the issue was resolved with version 1.19.3-1.1.1.  Thanks for the quick work even though I took ages to reply.
