### ISSUE TITLE
[Feature]: 1.20.6+ make the mod work fully server-side only

### ISSUE THREAD

**Issue by sternschnaube** [tristankechlo/RandomMobSizes#19]
### What happened?

Received unknown remote registry entries from server
FabricRegistrySync
Render thread
Registry entry (random_mob_sizes:sampler_types) is missing from local registry (minecraft:command_argument_type)
net.fabricmc.fabric.impl.client.registry.sync.FabricRegistryClientInit
Render thread
Registry remapping failed!
java.util.concurrent.CompletionException: net.fabricmc.fabric.impl.registry.sync.RemapException: Received a registry entry that is unknown to this client.
This is usually caused by a mismatched mod set between the client and server. See the client logs for more details.
The following registry entry namespaces may be related:

random_mob_sizes
	at net.fabricmc.fabric.impl.registry.sync.RegistrySyncManager.lambda$receivePacket$0(RegistrySyncManager.java:145)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
	at net.minecraft.class_1255.method_18859(class_1255.java:162)
	at net.minecraft.class_4093.mixinextras$bridge$method_18859$5(class_4093.java)
	at net.minecraft.class_4093.wrapOperation$dfl000$carpet-tis-addition$yeetUpdateSuppressionCrash_implForThreadExecutorTaskExecuting(class_4093.java:570)
	at net.minecraft.class_4093.method_18859(class_4093.java:23)
	at net.minecraft.class_1255.method_16075(class_1255.java:136)
	at net.minecraft.class_1255.method_5383(class_1255.java:121)
	at net.minecraft.class_310.method_1523(class_310.java:1275)
	at net.minecraft.class_310.method_1514(class_310.java:888)
	at net.minecraft.client.main.Main.main(Main.java:265)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: net.fabricmc.fabric.impl.registry.sync.RemapException: Received a registry entry that is unknown to this client.
This is usually caused by a mismatched mod set between the client and server. See the client logs for more details.
The following registry entry namespaces may be related:

random_mob_sizes
	at net.fabricmc.fabric.impl.registry.sync.RegistrySyncManager.checkRemoteRemap(RegistrySyncManager.java:364)
	at net.fabricmc.fabric.impl.registry.sync.RegistrySyncManager.apply(RegistrySyncManager.java:260)
	at net.fabricmc.fabric.impl.registry.sync.RegistrySyncManager.lambda$receivePacket$0(RegistrySyncManager.java:142)
	... 13 more

### Minecraft Version

1.20.6

### Modversion

Latest

### Modloader

Fabric

### Additional context

Since vanilla possibilities are used, I see not the need to force the mod for clients.

### Before submitting

- [X] I tested that the problem is caused by this mod (the bug does not happen when removing this mod)
- [X] I checked that there are no similar posts (open or closed) related to the this problem

**Comment by tristankechlo** [comment]
> This is usually caused by a mismatched mod set between the client and server.

Do you have the same mod-file on the server and client installed?

**Comment by sternschnaube** [comment]
No, as my title says, the mod should work server-side now since it's using the mechanics from vanilla. But that's not the case.

**Comment by tristankechlo** [comment]
Oh, now I understand :smile:, my bad.
Yes, in the recent update I moved the scaling value to the vanilla system.
But there are still fragments in the mod that need to present on both server and client (for example the commands to control the mod, (this caused your error)).

Never thought about going fully server-side only, but I guess it should be possible now.
So, thank you for the idea :+1:

**Comment by sternschnaube** [comment]
Great 😊

**Comment by tristankechlo** [comment]
the newest version (1.20.6-2.2.0) should work fully server-side only

**Comment by sternschnaube** [comment]
Thank you, that's awesome! I will test it later 😊

**Comment by juffis** [comment]
I can't find instructions how to install this mod on java server? I'm new to minecraft servers. I tried putting it into the server's plugin-folder, started the server, and nothing about this mod came up in the server console.
Also, where do I put the config-file on server side?

**Comment by tristankechlo** [comment]
You need a forge/fabric or neoforge server for this mod to work.  
When you start the server the folder `mods` is generated, where the jar file of the mod goes.  
The next restart of the server the config gets generated automatically.

**Comment by kanapuro** [comment]
Does 1.21.5 version work serverside only?

**Comment by tristankechlo** [comment]
Yes, everything above 1.20.6 should work server side only
